### PR TITLE
Typo fixed (clean)

### PR DESCRIPTION
**Pull request by vitasam**
Fix for *.d objects

### CODE REVIEW

**Comment by karlp** [comment]
fixed via 21ce202

**Comment by vitasam** [comment]
Hi,
could it bi that [21ce202](https://github.com/libopencm3/libopencm3-examples/commit/21ce202a07a1c57fd1c647eca7c7e1dfbe157fe6)  fix actually broke the build? make clean does not delete **.elf** file:
```
.../libopencm3-examples/examples/stm32/f1/stm32-maple/miniblink$ ls -l
total 216
-rw-rw-r-- 1 vitali vitali   865 kesä   7 22:31 Makefile
-rw-rw-r-- 1 vitali vitali  2157 kesä   7 22:31 miniblink.c
-rw-rw-r-- 1 vitali vitali   996 kesä   7 22:44 miniblink.d
-rwxrwxr-x 1 vitali vitali 99992 kesä   7 22:44 miniblink.elf
-rw-rw-r-- 1 vitali vitali 44443 kesä   7 22:44 miniblink.map
-rw-rw-r-- 1 vitali vitali 70268 kesä   7 22:44 miniblink.o
-rw-rw-r-- 1 vitali vitali   196 kesä   7 22:31 README.md
.../libopencm3-examples/examples/stm32/f1/stm32-maple/miniblink$ make clean
.../libopencm3-examples/examples/stm32/f1/stm32-maple/miniblink$ ls -l
total 96
-rw-rw-r-- 1 vitali vitali   865 kesä   7 22:31 Makefile
-rw-rw-r-- 1 vitali vitali  2157 kesä   7 22:31 miniblink.c
-rwxrwxr-x 1 vitali vitali 99992 kesä   7 22:44 miniblink.elf
-rw-rw-r-- 1 vitali vitali   196 kesä   7 22:31 README.md
```

**Comment by karlp** [comment]
works here (anothter computer, not the one I committed from)
```
karlp@beros:~/src/libopencm3-examples/examples/stm32/f1/stm32-maple/miniblink (master)$ make
karlp@beros:~/src/libopencm3-examples/examples/stm32/f1/stm32-maple/miniblink (master)$ ls
Makefile  miniblink.c  miniblink.d  miniblink.elf  miniblink.map  miniblink.o  README.md
karlp@beros:~/src/libopencm3-examples/examples/stm32/f1/stm32-maple/miniblink (master)$ make clean
karlp@beros:~/src/libopencm3-examples/examples/stm32/f1/stm32-maple/miniblink (master)$ ls
Makefile  miniblink.c  README.md
karlp@beros:~/src/libopencm3-examples/examples/stm32/f1/stm32-maple/miniblink (master)$
```

**Comment by vitasam** [comment]
In my case rm  -f with { ... } does not work. Is this a bash issue? I will re-test it on other linux 
```
.../libopencm3-examples/examples/stm32/f1/stm32-maple/miniblink$ **echo $BASH_VERSION
4.3.48(1)-release**
.../libopencm3-examples/examples/stm32/f1/stm32-maple/miniblink$ make clean V=1
Using ../../../../../libopencm3/ path to library
rm -f **miniblink.{elf,bin,hex,srec,list,map}** *.map generated.* miniblink.o miniblink.d
.../libopencm3-examples/examples/stm32/f1/stm32-maple/miniblink$ ls -l
total 96
-rw-rw-r-- 1 vitali vitali   865 kesä   7 22:31 Makefile
-rw-rw-r-- 1 vitali vitali  2157 kesä   7 22:31 miniblink.c
-rwxrwxr-x 1 vitali vitali 99992 kesä   8 07:45 miniblink.elf
-rw-rw-r-- 1 vitali vitali   196 kesä   7 22:31 README.md
```

**Comment by vitasam** [comment]
Same issue on another linux machine:

```
.../libopencm3-examples/examples/stm32/f1/stm32-maple/miniblink$ make V=1
Using ../../../../../libopencm3/ path to library
arm-none-eabi-gcc -Os -std=c99 -ggdb3 -mthumb -mcpu=cortex-m3 -msoft-float -mfix-cortex-m3-ldrd -Wextra -Wshadow -Wimplicit-function-declaration -Wredundant-decls -Wmissing-prototypes -Wstrict-prototypes -fno-common -ffunction-sections -fdata-sections  -MD -Wall -Wundef -DSTM32F1 -I../../../../../libopencm3//include  -o miniblink.o -c miniblink.c
arm-none-eabi-gcc --static -nostartfiles -T../stm32-maple.ld -mthumb -mcpu=cortex-m3 -msoft-float -mfix-cortex-m3-ldrd -ggdb3 -Wl,-Map=miniblink.map -Wl,--cref -Wl,--gc-sections -L../../../../../libopencm3//lib miniblink.o -lopencm3_stm32f1 -Wl,--start-group -lc -lgcc -lnosys -Wl,--end-group -o miniblink.elf
.../libopencm3-examples/examples/stm32/f1/stm32-maple/miniblink$ ls -l
total 220
-rw-rw-r-- 1 vitadmin vitadmin   865 Jun  8 04:52 Makefile
-rw-rw-r-- 1 vitadmin vitadmin   196 Jun  8 04:52 README.md
-rw-rw-r-- 1 vitadmin vitadmin  2157 Jun  8 04:52 miniblink.c
-rw-rw-r-- 1 vitadmin vitadmin   996 Jun  8 04:56 miniblink.d
-rwxrwxr-x 1 vitadmin vitadmin 99996 Jun  8 04:56 miniblink.elf
-rw-rw-r-- 1 vitadmin vitadmin 47403 Jun  8 04:56 miniblink.map
-rw-rw-r-- 1 vitadmin vitadmin 70272 Jun  8 04:56 miniblink.o
.../libopencm3-examples/examples/stm32/f1/stm32-maple/miniblink$ make clean V=1
Using ../../../../../libopencm3/ path to library
rm -f miniblink.{elf,bin,hex,srec,list,map} *.map generated.* miniblink.o miniblink.d
.../libopencm3-examples/examples/stm32/f1/stm32-maple/miniblink$ ls -l
total 96
-rw-rw-r-- 1 vitadmin vitadmin   865 Jun  8 04:52 Makefile
-rw-rw-r-- 1 vitadmin vitadmin   196 Jun  8 04:52 README.md
-rw-rw-r-- 1 vitadmin vitadmin  2157 Jun  8 04:52 miniblink.c
-rwxrwxr-x 1 vitadmin vitadmin 99996 Jun  8 04:56 miniblink.elf
```

**Comment by vitasam** [comment]
Adding `SHELL=/bin/bash` in to `libopencm3.rules.mk` did help

**Comment by karlp** [comment]
ok, I'll fix this to use more posix shell, I thought this was.  I think we're also using it elsewhere so I'll check for that too.

**Comment by karlp** [comment]
see fe6a2b5f13d1a938e6e1d5980b27682bd47407d2 for non-posixy shells.

**Comment by vitasam** [comment]
Now it works. Thanks!

**Pull request closed without merging**
