### PR TITLE
stm32f4-discovery/usb_cdcacm: fix OTG_FS_ID assignment

### PR DESCRIPTION
**Pull request by fjullien**
Signed-off-by: Franck Jullien franck.jullien@gmail.com

### CODE REVIEW

**Comment by karlp** [comment]
Is this the same bug as in https://github.com/libopencm3/libopencm3-examples/pull/88  ?

**Comment by karlp** [comment]
Note: when/if this or similar merges, need to cleanup it for all the other boards that use this example code.

**Comment by schodet** [comment]
I do not think `OTG_FS_ID` must be mapped, it is only used for OTG.

**Comment by karlp** [comment]
I don't either, I suspect there must have been other problems with the usb stack when this was proposed, probably related to vbus detection?

**Pull request closed without merging**
