### PR TITLE
stm32: cdcacm: fix array out of bounds write

### PR DESCRIPTION
**Pull request by spiccinini**
Remove unused code that is also an out of bounds write causing
memory corruption.

### CODE REVIEW

**Comment by karlp** [comment]
explain yourself better please.  I agree it looks like out of bounds, but it's very much being run, it's not unused.  should it be replaced with buf[len-1] = 0?

**Comment by manuelbl** [comment]
If the maximum packet of 64 bytes is received, it's clearly an out-of-bounds access. But most important: the statement is completely unnecessary as the next thing that happens is to fill the buffer with new data, i.e. write to it without reading it.

It looks like the remains of debugging code: zero-termination would be helpful if the received data was printed to a log of some kind.

**Comment by spiccinini** [comment]
@karlp I agree with @manuelbl , they seem to be leftovers from debugging, it does not make any sense to write a zero that is never sent. Also not all the cdcacm files had this line. I could not find from where this file or code was copy pasted to dig further (and maybe fix it there also if it is also there).  Anyway I tested the resulting code and it works (as expected). 

OT: @karlp You mentioned that new example projects are not considered to be merged,  I agree that it is very hard to maintain. Also you said that we may be adding API examples but I could not find where. I would like to add some, for instance an example of proper initialization of SPI for 8 bit transfers in L4 and others that have FIFO and read/write size defined access.

**Comment by karlp** [comment]
So, FYI, if you have to clarify your commit messages in github conversations, it's the sort of thing you should be putting in the commit message themselves, up front. there's no reason to try and make commit messages terse.

**Comment by spiccinini** [comment]
@karlp thanks for taking your time to improve my developer skills :) I'm sorry for wasting your time, when I wrote the commit message it seemed to me that I was explaining it well but now I see that I did not. 
I've force pushed an updated commit message.

**Comment by karlp** [comment]
merged thanks

**Pull request merged**
