### PR TITLE
Add example for Nucleo-L4R5ZI

### PR DESCRIPTION
**Pull request by Martchus**
A simple example making the LEDs on the board blink.

### CODE REVIEW

**Comment by asdil12** [comment]
The NUCLEO-L4R5ZI has ST-Link v2-1 (not v2) built in.
Here is the required patch:

```patch
diff --git a/examples/stm32/l4/nucleo-l4r5zi/blink/Makefile b/examples/stm32/l4/nucleo-l4r5zi/blink/Makefile
index 24498cb..2648b93 100644
--- a/examples/stm32/l4/nucleo-l4r5zi/blink/Makefile
+++ b/examples/stm32/l4/nucleo-l4r5zi/blink/Makefile
@@ -19,5 +19,7 @@ BINARY = blink
 
 LDSCRIPT = ../nucleo-l4r5zi.ld
 
+OOCD_INTERFACE  ?= stlink-v2-1
+
 include ../../Makefile.include
```

I was able to flash the board using `make flash` after I added this patch and compiled openocd with this patch: http://openocd.zylin.com/#/c/4447/

**Comment by Martchus** [comment]
Fixed the OOCD_INTERFACE, thanks.

**Comment by karlp** [comment]
and new versions of openocd will just let you use "stlink.cfg" and it will handle all three variants :)

**Comment by asdil12** [comment]
just succeded flashing with
```
OOCD_INTERFACE = stlink
```

**Comment by Martchus** [comment]
What would be missing to get this merged?

**Comment by karlp** [comment]
I've merged it to my miniblink repository, I'm not very interested in trying to maintain yet another variant of blink source here in this repo  but i'll leave it here if anyone finds this form more useful

**Comment by Martchus** [comment]
ok

**Pull request closed without merging**
